### PR TITLE
Add code preprocessing paper

### PR DESCRIPTION
**Pull request by arichelle**
This code is related to the following publication
"Assessing key decisions for transcriptomic data integration in biochemical networks"
Authors : Anne Richelle, Chintan Joshi and Nathan E Lewis
doi: https://doi.org/10.1101/301945 

I've introduced some modifications to take into account the comment of @tpfau and allow their integration with the existing functions for preprocessing transcriptomic data. Note that I've introduced some modifications in these current preprocessing functions(PR #1382) to access the id of gene mapped that is required for the analysis I perform in the publication above

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Do you need to have the `2018_DecisionsTranscriptomicIntegration/ModelRecon22.mat` model file inside the papers directory? Or can we download that model from somewhere else?

**Comment by arichelle** [comment]
Actually, I modified the gene list to have it in entrez ID... If really needed I can add a line in the preprocessing code to modify the Recon2.2 available on internet...

**Comment by arichelle** [comment]
Could you add the recon2.2 model in the repository of model of cobra ?
https://www.ebi.ac.uk/biomodels/MODEL1603150001

Le ven. 16 nov. 2018 à 00:24, Laurent Heirendt <notifications@github.com> a
écrit :

**Comment by laurentheirendt** [comment]
The `.xml` file of that model is quite large. Is that model anywhere distributed as a `.mat` file?

**Comment by tpfau** [comment]
No, its only available as sbml for all I know.

**Comment by laurentheirendt** [comment]
Thanks @arichelle and @tpfau 👍

**Pull request merged**
